spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.241.49:3306/internet_hospital?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    druid:
      aop-patterns: com.zjh.internethospitalservice.controller.*
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      async-init: true
  servlet:
    multipart:
      max-file-size: 2MB
  redis:
    host: 47.100.241.49
    port: 6379
    password:
  output:
    ansi:
      enabled: always
pagehelper:
  page-size-zero: true
  reasonable: true
swagger:
  docket:
    app:
        title: 蜗牛医疗API
        contact:
          name: Zeno
          email: zeno.jh.zhang@gmail.com
  global-operation-parameters:
      - name: Authorization
        description: token
        modelRef: String
        parameterType: header
        requeire: false
mapper:
  style: camelhumpAndLowercase
  not-empty: true
  check-example-entity-class: true
logging:
  file: C:/log/internetHospital.log
server:
  port: 8081
  ssl:
    key-store: 2007351_management.woniuyiliao.cn.pfx
    key-store-password: Rw7mU4q6
  max-http-header-size: 102400
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#支付宝相关
aliPay:
  serveUrl: https://openapi.alipaydev.com/gateway.do
  appId: 2016093000630797
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCTRZm5Crgo11JdqTdzE7SoicNSB8apIT3TPv+6vokN3PZGEHvCed3iBAb6LeELKCQZDpgbn8bJWIFkRJAJ5n4yggS3/klbrUaw14vg6hE4RCrnQeMxwDA4tXvL45THbRFA9nfDnyJPlFmI6SBRqcV/2DNIQjMUG62cB+2Xwr8Kn/PR8DaeH72EQr3M0gZmXPfBN5wmbE/cpU4TtuhxSAJq1UI+l0DOjQ1e9UbN7THDzdMUyHTU7+ZSWJTbZMcSKM7yA+c2ID097ROnR9BS/Qhxo4SexYi0V6oW6+8DojWpGT2FEFvfuNX7DyBCJs45XF87PUjClIGc9msxHBEH8u/BAgMBAAECggEBAIzgYFtM8LtItiaYL02qhP9PwQKgI544CS8hLXmSuAIF46NEM07mSqTgm1gIOST2AgniFwkdvwdt3WBv4aVG0mM4UpE68yt6Rov1tH2zCkPbmXrcYRt/L+GfYUu5aOGX6JBO9GOxvx2G2FsKPns/vog75Vpy0O+kRl9iihnJFfxvb6rsXBjXQZ6VPqBSrWLUI3IhNI++7K7SkAwjZ8ScbWrCbU6XuPo4egogKcZOWRWXRgghAYB4aN3cDiyq7YvYkM3lW0rkwXNUHuXFEgfjQiqC9umclv7d6rIeDJxQkEnyNIGBNtpbWyYm63v75ePkENnE2ZdnZtsZ9NqGqhZDGM0CgYEAzeqa88n9Y6JEPQsvnXvHFtdEs0useebLX0vlCBploQQoCQVlfrpXg0axJIHZ0U8vPYoI8Skyo3MKuj8+E9GTYx4+wURvMgYlfFJPDLyyhCEY/674R2XoYp+34d3HHk94IMrKljw3KwCOEjXUJhr7kMtJxNM6+/j80sZqUp1HrJcCgYEAtxd9agq4o52RMLmodnnElKcsJ1Uic3iQVPa1hEOb+fPWIL0RRXmAyyeyawO8UZAtfQ44kmLLtRQ/TeF25UWyHyH7KxizhWeXXSRnCDomOwABX1ylXm6phSayoBJLiFbMJYdfYvEWpiQ900U0azOZsvXAyuB+bpIXBXtHiotEWWcCgYAE8tlseHM9fL3VFbq8NyhOtTeyc2QevdwvWxyS+Edu+jGYHegVhpbp0b4aGYDJlfSVrwaN/SZ5ZR9h4Hk2crfvDuAFNwbRFfK6rSO3M6W6pSz7oBHZbWqLTDlYFUNeyBwj9Zuuxp2wy9+eMmr5y3Y2QZxxPX5SZeZ1jk0p1RvO2wKBgAqzLrshwUSekrucPgIef6SIWIY77XV+GEE+4cDHCriCzYLASeAbh7FXso+aekjx+haS3C+B4pHEiyaMBJzFg/FZ1QnhuawUL75bwEG01EMibvIZwfhQ00taxZmhOBTRrcCLtsFbgY1YFNzh8HxLWbIhtpCkqf7gPsQtPjMUjHwFAoGAWLJWW1tUqgt6Zo4Z1+2X0Acrwa/3xjtoMsScFIWr2tXm40HCOI6N/sNGxWOthCL88x/1mdQjYbiFvfd8q3wYBP+Oms85oQK3k9BWxpeOPTPZ1K+ig/ttuIKJgWY9A3BbJ7Es5CNjv+T+qBSMJfWMcmjDUNFVxANStAPPTdjQvFU=
  format: json
  charset: UTF-8
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuI+E7UwI74dlpR6JR2BiCdtvS6NUBLU6wBnY7KC+/Z31Ddtb0zDqQECBGCUl2Ej0u1nLxoqubeZthCIw25wokpqTYCXiEStt5o/13yWOyFaPLd8NUEus/1B7c1OWzh/BWTgc2yAAkoT9dl2WC5DQ35IrDkSUhdwpA3y/HG+1tyymnK6q4tjyfs9SXIAi1sOO2uCwcL80NkBke8CAIGQT6JYl2DFaEYjLK31oU0i21c+LoCYhxzAETSK4WZzCx6T0x6id2hljXzfKQ+lOp1X2QxJ8/rx+B20jqpigng2t0fKU9fHItdhM62NfqhnjpFEHYfIVGbiv4aa/tt2cUpxOkQIDAQAB
  signType: RSA2
